In [5]:
import numpy as np

In [20]:
class DenseLayer:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.random.randn(n_neurons)

    def forward(self, input):
        return np.dot(input, self.weights) + self.biases

In [21]:
from nnfs.datasets import spiral_data
import nnfs

nnfs.init()

In [22]:
X, y = spiral_data(samples=100, classes=3)
d = DenseLayer(2, 3)
output = d.forward(X)
print(output[:10])


[[-1.3342584  -1.3467175   0.69377315]
 [-1.3343632  -1.3466035   0.69372517]
 [-1.3345326  -1.3464001   0.69368625]
 [-1.3346803  -1.3461908   0.69371724]
 [-1.3348355  -1.3460034   0.69368374]
 [-1.3346127  -1.3463672   0.6935395 ]
 [-1.3351511  -1.3456407   0.6935786 ]
 [-1.335192   -1.3456451   0.6934609 ]
 [-1.3353828  -1.3454062   0.69343686]
 [-1.3355972  -1.3450974   0.6934921 ]]
