In [1]:
import numpy as np

In [3]:
import numpy as np

# Create a 3x4 matrix representing quarterly sales data for 3 products
# Rows: Products (A, B, C), Columns: Quarters (Q1, Q2, Q3, Q4)
sales_data = [[120, 150, 180, 200],   # Product A sales by quarter
              [90, 110, 130, 160],    # Product B sales by quarter
              [200, 220, 240, 280]]   # Product C sales by quarter

print("Sales Data Matrix:")
print(np.array(sales_data))
print()

# Sum all elements - total sales across all products and quarters
print("Total sales across all products and quarters:")
print(np.sum(sales_data))
print()

# Sum along axis=0 (columns) - total sales per quarter across all products
print("Total sales per quarter (sum down the rows):")
quarterly_totals = np.sum(sales_data, axis=0)
print(quarterly_totals)
print(f"Shape: {quarterly_totals.shape}")  # Results in 1D array with 4 elements
print()

# Sum along axis=1 (rows) - total sales per product across all quarters
print("Total sales per product (sum across the columns):")
product_totals = np.sum(sales_data, axis=1)
print(product_totals)
print(f"Shape: {product_totals.shape}")  # Results in 1D array with 3 elements
print()

# Sum along axis=0 with keepdims=True - preserves original dimensionality
print("Quarterly totals with dimensions preserved:")
quarterly_totals_2d = np.sum(sales_data, axis=0, keepdims=True)
print(quarterly_totals_2d)
print(f"Shape: {quarterly_totals_2d.shape}")  # Results in 2D array (1x4)
print()

# Sum along axis=1 with keepdims=True - preserves original dimensionality
print("Product totals with dimensions preserved:")
product_totals_2d = np.sum(sales_data, axis=1, keepdims=True)
print(product_totals_2d)
print(f"Shape: {product_totals_2d.shape}")  # Results in 2D array (3x1)
print()

# Find maximum values along axis=0 - best quarter performance for each product comparison
print("Best performing quarter for each position (max down the rows):")
print(np.max(sales_data, axis=0))
print()

# Find maximum values along axis=1 - best quarter performance for each product
print("Best quarter performance for each product (max across the columns):")
print(np.max(sales_data, axis=1))
print()

# Bonus: Additional useful operations
print("=== Additional Examples ===")

# Average sales per quarter and per product
print("Average sales per quarter:")
print(np.mean(sales_data, axis=0))
print()

print("Average sales per product:")
print(np.mean(sales_data, axis=1))
print()

# Standard deviation to see variability
print("Sales variability per product (standard deviation):")
print(np.std(sales_data, axis=1))

# Key Concepts Summary:
# - axis=0: Operations go DOWN the rows (column-wise operations)
# - axis=1: Operations go ACROSS the columns (row-wise operations)
# - keepdims=True: Maintains the original number of dimensions in the result
# - Without keepdims: Result has reduced dimensionality

Sales Data Matrix:
[[120 150 180 200]
 [ 90 110 130 160]
 [200 220 240 280]]

Total sales across all products and quarters:
2080

Total sales per quarter (sum down the rows):
[410 480 550 640]
Shape: (4,)

Total sales per product (sum across the columns):
[650 490 940]
Shape: (3,)

Quarterly totals with dimensions preserved:
[[410 480 550 640]]
Shape: (1, 4)

Product totals with dimensions preserved:
[[650]
 [490]
 [940]]
Shape: (3, 1)

Best performing quarter for each position (max down the rows):
[200 220 240 280]

Best quarter performance for each product (max across the columns):
[200 160 280]

=== Additional Examples ===
Average sales per quarter:
[136.66666667 160.         183.33333333 213.33333333]

Average sales per product:
[162.5 122.5 235. ]

Sales variability per product (standard deviation):
[30.31088913 25.86020108 29.58039892]


In [4]:
print("=== NUMPY BROADCASTING - SIMPLE EXAMPLES ===")
print()

# Example 1: Number + Array (Scalar Broadcasting)
print("1. Adding a number to an array:")
arr = np.array([1, 2, 3, 4])
result = arr + 10
print(f"   {arr} + 10 = {result}")
print("   The number 10 gets added to each element")
print()

# Example 2: Array + Array (Same Size)
print("2. Adding arrays of same size:")
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(f"   {arr1} + {arr2} = {result}")
print("   Each element adds to the corresponding element")
print()

# Example 3: 2D Array + 1D Array (Broadcasting)
print("3. Adding 1D array to 2D array:")
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
row_array = np.array([10, 20, 30])

print("   Matrix:")
print(matrix)
print(f"   + Array: {row_array}")

result = matrix + row_array
print("   Result:")
print(result)
print("   The 1D array gets added to each row of the matrix")
print()

# Example 4: 2D Array + Column Array
print("4. Adding column array to 2D array:")
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
col_array = np.array([[100],
                      [200]])

print("   Matrix:")
print(matrix)
print("   + Column:")
print(col_array)

result = matrix + col_array
print("   Result:")
print(result)
print("   The column values get added to each row")
print()

# Example 5: Simple Real Example
print("5. Real example - Adding tax to prices:")
# Prices for 3 products in 2 stores
prices = np.array([[10, 15, 20],    # Store 1 prices
                   [12, 18, 22]])   # Store 2 prices

# Tax rates for each product
tax_rates = np.array([0.1, 0.15, 0.2])  # 10%, 15%, 20%

print("   Prices:")
print(prices)
print(f"   Tax rates: {tax_rates}")

total_prices = prices * (1 + tax_rates)
print("   Prices with tax:")
print(total_prices)
print("   Each product gets its own tax rate applied")
print()

print("=== KEY POINTS ===")
print("• Broadcasting lets you do math with different sized arrays")
print("• Smaller arrays get 'stretched' to match bigger ones")
print("• Very useful for applying operations across rows or columns")
print("• No need to write loops - NumPy does it automatically")

=== NUMPY BROADCASTING - SIMPLE EXAMPLES ===

1. Adding a number to an array:
   [1 2 3 4] + 10 = [11 12 13 14]
   The number 10 gets added to each element

2. Adding arrays of same size:
   [1 2 3] + [4 5 6] = [5 7 9]
   Each element adds to the corresponding element

3. Adding 1D array to 2D array:
   Matrix:
[[1 2 3]
 [4 5 6]]
   + Array: [10 20 30]
   Result:
[[11 22 33]
 [14 25 36]]
   The 1D array gets added to each row of the matrix

4. Adding column array to 2D array:
   Matrix:
[[1 2 3]
 [4 5 6]]
   + Column:
[[100]
 [200]]
   Result:
[[101 102 103]
 [204 205 206]]
   The column values get added to each row

5. Real example - Adding tax to prices:
   Prices:
[[10 15 20]
 [12 18 22]]
   Tax rates: [0.1  0.15 0.2 ]
   Prices with tax:
[[11.   17.25 24.  ]
 [13.2  20.7  26.4 ]]
   Each product gets its own tax rate applied

=== KEY POINTS ===
• Broadcasting lets you do math with different sized arrays
• Smaller arrays get 'stretched' to match bigger ones
• Very useful for applyin